### ISSUE TITLE
Heavy abuse from people in my neighborhood. Hey man, People have been hiking in the I get home and my accountant and they won’t stop being really dumb about it. Is there anything you suggest I do that would make them sorry for doing this to me?

### ISSUE THREAD

**Issue by ThatsMRDavid** [niccokunzmann/download_latest#11]
![image](https://user-images.githubusercontent.com/42007863/103030308-27dd8b80-4521-11eb-94e7-51fe18be7886.png)

![image](https://user-images.githubusercontent.com/42007863/103030320-2dd36c80-4521-11eb-845d-15f1fa7bde4a.png)

Those are the pics I need others to help me with can you forward this to capable friends? They're hacking me and I'm not happy in my life because of them. Help

**Comment by niccokunzmann** [comment]
Hi, this is all fine. No worries. They just tell you this but it is normal configuration data.

I close this issue as it has nothing to do with this repository. You can still comment.
